### ISSUE TITLE
Travis-CI build with false positive

### ISSUE THREAD

**Issue by felipesabino** [seivan/SHActionSheetBlocks#2]
CI build is currently failing but reporting as success at https://travis-ci.org/seivan/SHActionSheetBlocks/builds/29939453#L107

```
$ xcodebuild -workspace TestsAndSample/Sample.xcworkspace -scheme Tests -sdk iphonesimulator7.0 test | xcpretty -c
xcodebuild: error: Failed to build workspace Sample with scheme Tests.
	Reason: Xcode cannot run using the selected device.
```

**Comment by seivan** [comment]
@felipesabino Thanks, I've been running them locally and the tests are green, but I haven't updated the .travims.yml to work with newer SDK

```
xcodebuild -workspace TestsAndSample/Sample.xcworkspace -scheme Tests -sdk iphonesimulator8.1 test | xcpretty -c
```

Fixes it :)

**Comment by seivan** [comment]
Reopened it because it still seems to break on TravisCi but the tests run locally.
$ xcodebuild -workspace TestsAndSample/Sample.xcworkspace -scheme Tests -sdk iphonesimulator8.1 test | xcpretty -c

https://travis-ci.org/seivan/SHActionSheetBlocks/builds/54820064 

I've asked TravisCi to look into it for now.

**Comment by joshk** [comment]
Hi, Josh here from Travis CI. Is 8.1 part of XCode 6.2?

**Comment by seivan** [comment]
@joshk Thank you so much for replying here! 

Version 6.1.1 (6A2008a) has 8.1

Not sure about 6.2, I am on 6.3 Beta 3 and 6.1

What are you guys running on your end?

**Comment by seivan** [comment]
Missing link:
http://twitter.com/travisci/status/578048193306370048
```
“osx_image: xcode611”
```
Thanks a bunch @joshk

**Comment by felipesabino** [comment]
@seivan Actually you should set your [`.travis.yml` script](https://github.com/seivan/SHActionSheetBlocks/blob/develop/.travis.yml#L5) to fail properly as well using `set -e` 

May be sth like

```
script:  set -e && xcodebuild -workspace TestsAndSample/Sample.xcworkspace -scheme Tests -sdk iphonesimulator8.1 test | xcpretty -c
```

**Comment by seivan** [comment]
@felipesabino I am not sure why that is necessary now. It certainly was not previously. When they failed, they were red. 
Sample: https://travis-ci.org/seivan/SHActionSheetBlocks/builds/9593733

**Comment by joshk** [comment]
Could you explain why `set -e` is needed?

**Comment by felipesabino** [comment]
@joshk I believe `set-e` would prevent builds like [this](https://travis-ci.org/seivan/SHActionSheetBlocks/builds/29939453#L107) to report a false positive, wouldn't it?
